/*

requirements

1266. Find the Difference
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example
Example：

Input：s = "abcd"，t = "abcde"
Output：'e'
Explanation：'e' is the letter that was added.
*/

class Solution {
public:
    /**
     * @param s: a string
     * @param t: a string
     * @return: the letter that was added in t
     */
    char findTheDifference(string &s, string &t) {
        // Write your code here
        if (s.empty()) return t[0];
        char res = s[0];
        size_t m = s.length(), n = t.length();
        for (size_t i = 1; i < m + n; ++i)
        {
            if (i < m) res = res ^ s[i];
            else res = res ^ t[i - m];
        }
        return res;
    }
};